### ISSUE TITLE
how to use + how to add new sunXi-aXX.dtsi

### ISSUE THREAD

**Issue by ucy74** [mripard/sunxi-babelfish#1]
Is this effect file to add to final bootload directory?
Or creates patch for existing zImage?
Where to put base .fex file?

**Comment by mripard** [comment]
It wraps around the kernel image, providing an image that behaves like a kernel image from the bootloader point of view. The fex file has to be loaded at 0x4310000, like the allwinner bootloader and kernel expects.

But this is rather old, and has never been really updated, so it probably won't work any more. Feel free to pick up the work if you want

**Comment by ucy74** [comment]
how to use your code - drop to compile with kernel or standalone?

**Comment by mripard** [comment]
You need to compile a zImage first and then compile this.

You have some discussion and how to use it in that mail:http://lists.infradead.org/pipermail/linux-arm-kernel/2014-January/223654.html
